// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vdpadpdk-msgs.proto

package vdpadpdk

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetSocketpathRequest struct {
	PciAddress           string   `protobuf:"bytes,1,opt,name=pciAddress,proto3" json:"pciAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSocketpathRequest) Reset()         { *m = GetSocketpathRequest{} }
func (m *GetSocketpathRequest) String() string { return proto.CompactTextString(m) }
func (*GetSocketpathRequest) ProtoMessage()    {}
func (*GetSocketpathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_vdpadpdk_msgs_eb2654b0975dee66, []int{0}
}
func (m *GetSocketpathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSocketpathRequest.Unmarshal(m, b)
}
func (m *GetSocketpathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSocketpathRequest.Marshal(b, m, deterministic)
}
func (dst *GetSocketpathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSocketpathRequest.Merge(dst, src)
}
func (m *GetSocketpathRequest) XXX_Size() int {
	return xxx_messageInfo_GetSocketpathRequest.Size(m)
}
func (m *GetSocketpathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSocketpathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSocketpathRequest proto.InternalMessageInfo

func (m *GetSocketpathRequest) GetPciAddress() string {
	if m != nil {
		return m.PciAddress
	}
	return ""
}

type GetSocketpathResponse struct {
	Socketpath           string   `protobuf:"bytes,1,opt,name=socketpath,proto3" json:"socketpath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSocketpathResponse) Reset()         { *m = GetSocketpathResponse{} }
func (m *GetSocketpathResponse) String() string { return proto.CompactTextString(m) }
func (*GetSocketpathResponse) ProtoMessage()    {}
func (*GetSocketpathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_vdpadpdk_msgs_eb2654b0975dee66, []int{1}
}
func (m *GetSocketpathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSocketpathResponse.Unmarshal(m, b)
}
func (m *GetSocketpathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSocketpathResponse.Marshal(b, m, deterministic)
}
func (dst *GetSocketpathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSocketpathResponse.Merge(dst, src)
}
func (m *GetSocketpathResponse) XXX_Size() int {
	return xxx_messageInfo_GetSocketpathResponse.Size(m)
}
func (m *GetSocketpathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSocketpathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSocketpathResponse proto.InternalMessageInfo

func (m *GetSocketpathResponse) GetSocketpath() string {
	if m != nil {
		return m.Socketpath
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSocketpathRequest)(nil), "vdpadpdk.GetSocketpathRequest")
	proto.RegisterType((*GetSocketpathResponse)(nil), "vdpadpdk.GetSocketpathResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VdpaDpdkClient is the client API for VdpaDpdk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VdpaDpdkClient interface {
	GetSocketpath(ctx context.Context, in *GetSocketpathRequest, opts ...grpc.CallOption) (*GetSocketpathResponse, error)
}

type vdpaDpdkClient struct {
	cc *grpc.ClientConn
}

func NewVdpaDpdkClient(cc *grpc.ClientConn) VdpaDpdkClient {
	return &vdpaDpdkClient{cc}
}

func (c *vdpaDpdkClient) GetSocketpath(ctx context.Context, in *GetSocketpathRequest, opts ...grpc.CallOption) (*GetSocketpathResponse, error) {
	out := new(GetSocketpathResponse)
	err := c.cc.Invoke(ctx, "/vdpadpdk.VdpaDpdk/GetSocketpath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VdpaDpdkServer is the server API for VdpaDpdk service.
type VdpaDpdkServer interface {
	GetSocketpath(context.Context, *GetSocketpathRequest) (*GetSocketpathResponse, error)
}

func RegisterVdpaDpdkServer(s *grpc.Server, srv VdpaDpdkServer) {
	s.RegisterService(&_VdpaDpdk_serviceDesc, srv)
}

func _VdpaDpdk_GetSocketpath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSocketpathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VdpaDpdkServer).GetSocketpath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vdpadpdk.VdpaDpdk/GetSocketpath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VdpaDpdkServer).GetSocketpath(ctx, req.(*GetSocketpathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VdpaDpdk_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vdpadpdk.VdpaDpdk",
	HandlerType: (*VdpaDpdkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSocketpath",
			Handler:    _VdpaDpdk_GetSocketpath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vdpadpdk-msgs.proto",
}

func init() { proto.RegisterFile("vdpadpdk-msgs.proto", fileDescriptor_vdpadpdk_msgs_eb2654b0975dee66) }

var fileDescriptor_vdpadpdk_msgs_eb2654b0975dee66 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4b, 0x29, 0x48,
	0x4c, 0x29, 0x48, 0xc9, 0xd6, 0xcd, 0x2d, 0x4e, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x80, 0x09, 0x2a, 0x99, 0x71, 0x89, 0xb8, 0xa7, 0x96, 0x04, 0xe7, 0x27, 0x67, 0xa7, 0x96,
	0x14, 0x24, 0x96, 0x64, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x71, 0x71, 0x15,
	0x24, 0x67, 0x3a, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x21, 0x89, 0x28, 0x99, 0x73, 0x89, 0xa2, 0xe9, 0x2b, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x05, 0x69,
	0x2c, 0x86, 0x8b, 0xc2, 0x34, 0x22, 0x44, 0x8c, 0xe2, 0xb8, 0x38, 0xc2, 0x52, 0x0a, 0x12, 0x5d,
	0x0a, 0x52, 0xb2, 0x85, 0x82, 0xb8, 0x78, 0x51, 0x0c, 0x11, 0x92, 0xd3, 0x83, 0x39, 0x4c, 0x0f,
	0x9b, 0xab, 0xa4, 0xe4, 0x71, 0xca, 0x43, 0x6c, 0x57, 0x62, 0x48, 0x62, 0x03, 0xfb, 0xd0, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x07, 0x6b, 0xd4, 0xf8, 0x00, 0x00, 0x00,
}
