#!/bin/sh

set -e

HTTPD_SYS_BINARY_DIR="/usr/bin"
SEASTAR_HTTPD_DPDK_DYNAMIC_FILE="/var/run/seastar/seastar_dpdk_dynamic.conf"
SEASTAR_HTTPD_IP_DYNAMIC_FILE="/var/run/seastar/seastar_ip_dynamic.conf"

if [ -f $SEASTAR_HTTPD_DPDK_DYNAMIC_FILE ]; then
   SEASTAR_HTTPD_DPDK_DYNAMIC=`cat $SEASTAR_HTTPD_DPDK_DYNAMIC_FILE`
   rm $SEASTAR_HTTPD_DPDK_DYNAMIC_FILE
fi

if [ -f $SEASTAR_HTTPD_IP_DYNAMIC_FILE ]; then
   SEASTAR_POD_HTTPD_IPADDR=`cat $SEASTAR_HTTPD_IP_DYNAMIC_FILE`
   rm $SEASTAR_HTTPD_IP_DYNAMIC_FILE
elif [ -z $SEASTAR_POD_HTTPD_IPADDR ]; then
	SEASTAR_POD_HTTPD_IPADDR="192.168.133.2"
fi

DPDK_ARGS="$SEASTAR_HTTPD_DPDK_DYNAMIC"
DPDK_ARGS="$DPDK_ARGS --no-pci"
DPDK_ARGS="$DPDK_ARGS --single-file-segments"
DPDK_ARGS="$DPDK_ARGS --iova-mode va"
DPDK_ARGS="$DPDK_ARGS -l 0,1,2"

CLI_PARAMS="--network-stack native"
CLI_PARAMS="$CLI_PARAMS --dpdk-pmd"
CLI_PARAMS="$CLI_PARAMS --dhcp 0"
CLI_PARAMS="$CLI_PARAMS --host-ipv4-addr $SEASTAR_POD_HTTPD_IPADDR"
CLI_PARAMS="$CLI_PARAMS --netmask-ipv4-addr 255.255.255.0"
CLI_PARAMS="$CLI_PARAMS --collectd 0"
CLI_PARAMS="$CLI_PARAMS --smp 3"
CLI_PARAMS="$CLI_PARAMS --hugepages /dev/hugepages"
CLI_PARAMS="$CLI_PARAMS -m 2G"
CLI_PARAMS="$CLI_PARAMS --lro off"
CLI_PARAMS="$CLI_PARAMS --argv0"

echo "CLI_PARAMS=$CLI_PARAMS"
echo "DPDK_ARGS=\"$DPDK_ARGS\""
exec $HTTPD_SYS_BINARY_DIR/httpd $CLI_PARAMS "$DPDK_ARGS"
