apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vdpa-daemon-amd64
  labels:
    tier: node
    app: vdpadpdk
    name: vdpadpdk
spec:
  selector:
    matchLabels:
      name: vdpadpdk
  template:
    metadata:
      labels:
        tier: node
        app: vdpadpdk
        name: vdpadpdk
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: vdpadpdk-daemonset
        image: vdpa-daemonset
        imagePullPolicy: Never
        startupProbe:
          failureThreshold: 30
          periodSeconds: 10
        securityContext:
          privileged: true
        volumeMounts:
        - name: vhostsock
          mountPath: /var/run/vdpa/
          readOnly: false
        - name: log
          mountPath: /var/log
        - name: hugepage
          mountPath: /dev/hugepages
        resources:
          requests:
            memory: 1Gi
          limits:
            hugepages-1Gi: 2Gi
        #command: ["sleep", "infinity"]
      - name: vdpa-grpc-server
        image: vdpa-grpc-server
        imagePullPolicy: Never
        startupProbe:
          failureThreshold: 30
          periodSeconds: 10
        securityContext:
          privileged: true
        volumeMounts:
          - name: vhostsock
            mountPath: /var/run/vdpa/
            readOnly: false
          - name: log
            mountPath: /var/log
        #command: ["sleep", "infinity"]
      volumes:
        - name: vhostsock
          hostPath:
            path: /var/run/vdpa/
        - name: log
          hostPath:
            path: /var/log
        - name: hugepage
          emptyDir:
            medium: HugePages
