## Deploys a traffic generator and a traffic sink on different nodes
## The node label "vdpa-test-role: gen" is used to place the generator pod
## The node label "vdpa-test-role: sink" is used to place the sink pod
# Eg:
# kubectl label nodes <gen-nodename> vdpa-test-role-gen=true
# kubectl label nodes <sink-nodename> vdpa-test-role-sink=true
apiVersion: v1
kind: Pod
metadata:
  name: vdpa-pod-gen
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
        "name": "vdpa-mlx-vhost-net-1000",
        "mac": "0C:FE:C0:FF:EE:00"
      },
      {
        "name": "vdpa-mlx-vhost-net-2000",
        "mac": "0C:FE:C0:FF:EE:01"
      }
      ]'
spec:
  nodeSelector:
    vdpa-test-role-gen: "true"
  containers:
  - name: vdpa-dpd-app
    image: dpdk-app-centos:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        memory: 1Gi
        #memory: 2Mi
        intel.com/vdpa_mlx_vhost: '2'
      limits:
        hugepages-1Gi: 2Gi
        #hugepages-2Mi: 2048Mi
        intel.com/vdpa_mlx_vhost: '2'
    # Uncomment for debugging :
    #command: ["sleep"]
    #args: ["infinity"]
    env:
      - name: DPDK_SAMPLE_APP
        value: "testpmd"
      - name: TESTPMD_EXTRA_ARGS
        value: "--forward-mode=txonly"
  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  - name: hugepage
    emptyDir:
      medium: HugePages
---
apiVersion: v1
kind: Pod
metadata:
  name: vdpa-pod-sink
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
        "name": "vdpa-mlx-vhost-net-1000",
        "mac": "0C:FE:C0:FF:EE:10"
      },
      {
        "name": "vdpa-mlx-vhost-net-2000",
        "mac": "0C:FE:C0:FF:EE:11"
      }
      ]'
spec:
  nodeSelector:
    vdpa-test-role-sink: "true"
  containers:
  - name: vdpa-example
    image: dpdk-app-centos:latest
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        memory: 1Gi
        #memory: 2Mi
        intel.com/vdpa_mlx_vhost: '2'
      limits:
        hugepages-1Gi: 2Gi
        #hugepages-2Mi: 2048Mi
        intel.com/vdpa_mlx_vhost: '2'
    # Uncomment for debugging :
    #command: ["sleep"]
    #args: ["infinity"]
    env:
      - name: DPDK_SAMPLE_APP
        value: "testpmd"
      - name: TESTPMD_EXTRA_ARGS
        value: "--forward-mode=rxonly"
  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  - name: hugepage
    emptyDir:
      medium: HugePages
